/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/account': RouteRecordInfo<'/account', '/account', Record<never, never>, Record<never, never>>,
    '/accounts': RouteRecordInfo<'/accounts', '/accounts', Record<never, never>, Record<never, never>>,
    '/assistant/': RouteRecordInfo<'/assistant/', '/assistant', Record<never, never>, Record<never, never>>,
    '/auth/callback': RouteRecordInfo<'/auth/callback', '/auth/callback', Record<never, never>, Record<never, never>>,
    '/broadcasts': RouteRecordInfo<'/broadcasts', '/broadcasts', Record<never, never>, Record<never, never>>,
    '/calendar': RouteRecordInfo<'/calendar', '/calendar', Record<never, never>, Record<never, never>>,
    '/contacts/': RouteRecordInfo<'/contacts/', '/contacts', Record<never, never>, Record<never, never>>,
    '/content/': RouteRecordInfo<'/content/', '/content', Record<never, never>, Record<never, never>>,
    '/content/relationship-builder': RouteRecordInfo<'/content/relationship-builder', '/content/relationship-builder', Record<never, never>, Record<never, never>>,
    '/create': RouteRecordInfo<'/create', '/create', Record<never, never>, Record<never, never>>,
    '/email': RouteRecordInfo<'/email', '/email', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/offer': RouteRecordInfo<'/offer', '/offer', Record<never, never>, Record<never, never>>,
    '/ops/customers': RouteRecordInfo<'/ops/customers', '/ops/customers', Record<never, never>, Record<never, never>>,
    '/ops/sites': RouteRecordInfo<'/ops/sites', '/ops/sites', Record<never, never>, Record<never, never>>,
    '/pages/new': RouteRecordInfo<'/pages/new', '/pages/new', Record<never, never>, Record<never, never>>,
    '/pricing': RouteRecordInfo<'/pricing', '/pricing', Record<never, never>, Record<never, never>>,
    '/privacy': RouteRecordInfo<'/privacy', '/privacy', Record<never, never>, Record<never, never>>,
    '/protocol': RouteRecordInfo<'/protocol', '/protocol', Record<never, never>, Record<never, never>>,
    '/sites/[username]': RouteRecordInfo<'/sites/[username]', '/sites/:username', { username: ParamValue<true> }, { username: ParamValue<false> }>,
    '/sites/[username]/build': RouteRecordInfo<'/sites/[username]/build', '/sites/:username/build', { username: ParamValue<true> }, { username: ParamValue<false> }>,
    '/support': RouteRecordInfo<'/support', '/support', Record<never, never>, Record<never, never>>,
    '/survey': RouteRecordInfo<'/survey', '/survey', Record<never, never>, Record<never, never>>,
    '/terms': RouteRecordInfo<'/terms', '/terms', Record<never, never>, Record<never, never>>,
  }
}
